name: PC_denoiser
channels:
  - pytorch
  - defaults
  - conda-forge
  - davidcaron
  - fvcore
  - iopath
dependencies:
  - python=3.7.1
  - pclpy=0.12.0
  - scipy=1.7.3
  - plyfile=0.8.1
  - scikit-learn=1.0.2
  - chardet=4.0.0
  - pytorch==1.12.1
  - torchvision==0.13.1
  - torchaudio==0.12.1
  - cudatoolkit=11.3
  - matplotlib=3.5.3
  - pillow=8.2.0
  - tqdm=4.67.1
  - pyyaml=6.0
  - easydict=1.13
  - tensorboard=1.15.0
  - pandas=1.2.3
  - fvcore=0.1.5.post20210915
  - iopath=0.1.9
  - requests==2.28.1
  - h5py
  - pytorch-lightning
  - flask